apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catalog-stable
spec:
  ingressClassName: nginx
  rules:
  - host: retail.local
    http:
      paths:
      - path: /catalog
        pathType: Prefix
        backend:
          service:
            name: catalog
            port:
              number: 8080
