services:
  ui:
    ports:
      - 8888:8080
    environment:
      - JAVA_OPTS=-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
      - SERVER_TOMCAT_ACCESSLOG_ENABLED=true
      - RETAIL_UI_ENDPOINTS_CATALOG=${RETAIL_UI_ENDPOINTS_CATALOG:-http://host.docker.internal:8081}
      - RETAIL_UI_ENDPOINTS_CARTS=${RETAIL_UI_ENDPOINTS_CARTS:-http://host.docker.internal:8082}
      - RETAIL_UI_ENDPOINTS_CHECKOUT=${RETAIL_UI_ENDPOINTS_CHECKOUT:-http://host.docker.internal:8085}
      - RETAIL_UI_ENDPOINTS_ORDERS=${RETAIL_UI_ENDPOINTS_ORDERS:-http://host.docker.internal:8083}
    hostname: ui
    build:
      context: .
    restart: always
    mem_limit: 512m
    cap_drop:
      - ALL
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -f http://localhost:8080/actuator/health || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 15s
    develop:
      watch:
        - action: rebuild
          path: src
        - action: rebuild
          path: pom.xml
