apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: catalog-routing
spec:
  hosts:
    - "retail.local"
  gateways:
    - retail-gateway
  http:
    - route:
        - destination:
            host: catalog.default.svc.cluster.local
            port:
              number: 8080

