apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
data:
  RETAIL_UI_ENDPOINTS_CATALOG: http://catalog:8080
  RETAIL_UI_ENDPOINTS_CARTS: http://cart:8080
  RETAIL_UI_ENDPOINTS_CHECKOUT: http://checkout:8080
  RETAIL_UI_ENDPOINTS_ORDERS: http://orders:8080


# path to the product images
#RETAIL_UI_PRODUCT_IMAGES_PATH: /app/src/main/resources/static/images